# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Registration.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog


class LoginWindow(QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(568, 349)
        Dialog.setMinimumSize(QtCore.QSize(568, 349))
        self.pic_background = QtWidgets.QLabel(Dialog)
        self.pic_background.setGeometry(QtCore.QRect(0, 0, 561, 341))
        self.pic_background.setText("")
        self.pic_background.setPixmap(QtGui.QPixmap("Design/download.png"))
        self.pic_background.setObjectName("pic_background")
        self.title = QtWidgets.QLabel(Dialog)
        self.title.setGeometry(QtCore.QRect(110, 10, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Poor Richard")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setTextFormat(QtCore.Qt.AutoText)
        self.title.setObjectName("title")
        self.text_log_in = QtWidgets.QLabel(Dialog)
        self.text_log_in.setGeometry(QtCore.QRect(190, 50, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Poor Richard")
        font.setPointSize(17)
        self.text_log_in.setFont(font)
        self.text_log_in.setObjectName("text_log_in")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(350, 140, 181, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.text_username = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.text_username.setFont(font)
        self.text_username.setObjectName("text_username")
        self.verticalLayout.addWidget(self.text_username)
        self.enter_username = QtWidgets.QLineEdit(self.layoutWidget)
        self.enter_username.setText("")
        self.enter_username.setObjectName("enter_username")
        self.verticalLayout.addWidget(self.enter_username)
        self.text_password = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.text_password.setFont(font)
        self.text_password.setObjectName("text_password")
        self.verticalLayout.addWidget(self.text_password)
        self.enter_password = QtWidgets.QLineEdit(self.layoutWidget)
        self.enter_password.setText("")
        self.enter_password.setObjectName("enter_password")
        self.verticalLayout.addWidget(self.enter_password)
        self.butt_login = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.butt_login.setFont(font)
        self.butt_login.setObjectName("butt_login")
        self.verticalLayout.addWidget(self.butt_login)
        self.butt_registration = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.butt_registration.setFont(font)
        self.butt_registration.setObjectName("butt_registration")
        self.verticalLayout.addWidget(self.butt_registration)
        self.butt_exit = QtWidgets.QPushButton(self.layoutWidget)
        self.butt_exit.setObjectName("butt_exit")
        self.verticalLayout.addWidget(self.butt_exit)
        self.text_password.raise_()
        self.butt_login.raise_()
        self.butt_registration.raise_()
        self.enter_username.raise_()
        self.butt_exit.raise_()
        self.enter_password.raise_()
        self.text_username.raise_()
        self.pic_background.lower()
        self.layoutWidget.raise_()
        self.title.raise_()
        self.text_log_in.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title.setText(_translate("Dialog", "Guitar Inventory"))
        self.text_log_in.setText(_translate("Dialog", "LOG IN"))
        self.text_username.setText(_translate("Dialog", "ENTER USERNAME:"))
        self.enter_username.setPlaceholderText(_translate("Dialog", "Username"))
        self.text_password.setText(_translate("Dialog", "ENTER PASSWORD"))
        self.enter_password.setPlaceholderText(_translate("Dialog", "Password"))
        self.butt_login.setText(_translate("Dialog", "LOG IN"))
        self.butt_registration.setText(_translate("Dialog", "REGISTER"))
        self.butt_exit.setText(_translate("Dialog", "EXIT"))
