# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class mainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(634, 477)
        MainWindow.setMinimumSize(QtCore.QSize(634, 477))
        MainWindow.setMaximumSize(QtCore.QSize(634, 477))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(50, 80, 531, 251))
        self.tableWidget.setMaximumSize(QtCore.QSize(531, 251))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 340, 291, 71))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Design/guitar.png"))
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 10, 591, 20))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.text_welcomeuser = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.text_welcomeuser.setFont(font)
        self.text_welcomeuser.setObjectName("text_welcomeuser")
        self.horizontalLayout.addWidget(self.text_welcomeuser)
        spacerItem = QtWidgets.QSpacerItem(458, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.butt_logout = QtWidgets.QPushButton(self.layoutWidget)
        self.butt_logout.setObjectName("butt_logout")
        self.horizontalLayout.addWidget(self.butt_logout)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(30, 30, 591, 41))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.butt_addguitar = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.butt_addguitar.setFont(font)
        self.butt_addguitar.setObjectName("butt_addguitar")
        self.horizontalLayout_2.addWidget(self.butt_addguitar)
        self.butt_edit = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.butt_edit.setFont(font)
        self.butt_edit.setObjectName("butt_edit")
        self.horizontalLayout_2.addWidget(self.butt_edit)
        self.butt_remove = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.butt_remove.setFont(font)
        self.butt_remove.setObjectName("butt_remove")
        self.horizontalLayout_2.addWidget(self.butt_remove)
        self.butt_lend = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.butt_lend.setFont(font)
        self.butt_lend.setObjectName("butt_lend")
        self.horizontalLayout_2.addWidget(self.butt_lend)
        self.butt_return = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.butt_return.setFont(font)
        self.butt_return.setObjectName("butt_return")
        self.horizontalLayout_2.addWidget(self.butt_return)
        self.butt_history = QtWidgets.QPushButton(self.centralwidget)
        self.butt_history.setGeometry(QtCore.QRect(250, 411, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.butt_history.setFont(font)
        self.butt_history.setObjectName("butt_history")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 634, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Number"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Type"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Color"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Type of wood"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Borrowed"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Returned"))
        self.text_welcomeuser.setText(_translate("MainWindow", "WELCOME, USER"))
        self.butt_logout.setText(_translate("MainWindow", "LOG OUT"))
        self.butt_addguitar.setText(_translate("MainWindow", "ADD GUITAR"))
        self.butt_edit.setText(_translate("MainWindow", "EDIT GUITAR"))
        self.butt_remove.setText(_translate("MainWindow", "REMOVE GUITAR"))
        self.butt_lend.setText(_translate("MainWindow", "LEND GUITAR"))
        self.butt_return.setText(_translate("MainWindow", "RETURN GUITAR"))
        self.butt_history.setText(_translate("MainWindow", "GUITAR HISTORY"))

